name: Pull Docker Image

on:
  workflow_dispatch: # 允许在 GitHub 网页端手动触发

jobs:
  pull-and-package:
    runs-on: ubuntu-latest # 使用 GitHub 提供的免费 Linux 虚拟机

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: |
          echo "开始拉取 atmoz/sftp 镜像..."
          docker pull atmoz/sftp

      - name: Save Docker image as tar file
        run: |
          echo "正在将镜像打包为 sftp.tar..."
          docker save -o sftp.tar atmoz/sftp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sftp-docker-image # 下载时的压缩包名称
          path: sftp.tar          # 要上传的文件路径
          retention-days: 7       # 文件保留 7 天
