name: Pull and Save Docker Images

on:
  workflow_dispatch:

jobs:
  pull-save:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and save images
        run: |
          docker pull maven:3.9-eclipse-temurin-17
          docker save maven:3.9-eclipse-temurin-17 -o maven.tar
          docker pull rockylinux:9
          docker save rockylinux:9 -o rockylinux.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            maven.tar
            rockylinux.tar
          retention-days: 1
